# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/mrp/protobuf/SendPackedVirtualTouchEventMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyatv.mrp.protobuf import ProtocolMessage_pb2 as pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2
from pyatv.mrp.protobuf import VirtualTouchEvent_pb2 as pyatv_dot_mrp_dot_protobuf_dot_VirtualTouchEvent__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/mrp/protobuf/SendPackedVirtualTouchEventMessage.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n;pyatv/mrp/protobuf/SendPackedVirtualTouchEventMessage.proto\x1a(pyatv/mrp/protobuf/ProtocolMessage.proto\x1a*pyatv/mrp/protobuf/VirtualTouchEvent.proto\"2\n\"SendPackedVirtualTouchEventMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c:a\n\"sendPackedVirtualTouchEventMessage\x12\x10.ProtocolMessage\x18/ \x01(\x0b\x32#.SendPackedVirtualTouchEventMessage')
  ,
  dependencies=[pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.DESCRIPTOR,pyatv_dot_mrp_dot_protobuf_dot_VirtualTouchEvent__pb2.DESCRIPTOR,])


SENDPACKEDVIRTUALTOUCHEVENTMESSAGE_FIELD_NUMBER = 47
sendPackedVirtualTouchEventMessage = _descriptor.FieldDescriptor(
  name='sendPackedVirtualTouchEventMessage', full_name='sendPackedVirtualTouchEventMessage', index=0,
  number=47, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_SENDPACKEDVIRTUALTOUCHEVENTMESSAGE = _descriptor.Descriptor(
  name='SendPackedVirtualTouchEventMessage',
  full_name='SendPackedVirtualTouchEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SendPackedVirtualTouchEventMessage.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['SendPackedVirtualTouchEventMessage'] = _SENDPACKEDVIRTUALTOUCHEVENTMESSAGE
DESCRIPTOR.extensions_by_name['sendPackedVirtualTouchEventMessage'] = sendPackedVirtualTouchEventMessage
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendPackedVirtualTouchEventMessage = _reflection.GeneratedProtocolMessageType('SendPackedVirtualTouchEventMessage', (_message.Message,), dict(
  DESCRIPTOR = _SENDPACKEDVIRTUALTOUCHEVENTMESSAGE,
  __module__ = 'pyatv.mrp.protobuf.SendPackedVirtualTouchEventMessage_pb2'
  # @@protoc_insertion_point(class_scope:SendPackedVirtualTouchEventMessage)
  ))
_sym_db.RegisterMessage(SendPackedVirtualTouchEventMessage)

sendPackedVirtualTouchEventMessage.message_type = _SENDPACKEDVIRTUALTOUCHEVENTMESSAGE
pyatv_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(sendPackedVirtualTouchEventMessage)

# @@protoc_insertion_point(module_scope)
